name=ARAM_Metal_Orchestra
version=1.0.1
author=A.R.A.M. - American Robotics Assisted Manufacturing
maintainer=A.R.A.M. - American Robotics Assisted Manufacturing <support@aram-usa.com>
sentence=Construct Instrument Using Toggle Actuators
depends=ARAM_Toggle_Actuator (>=1.0.5)
paragraph=This library is intended for use with ARAM Metal Orchestra Actuators. Add one or more actuators to your instrument and play notes, or connect to a MIDI Bluetooth server as shown in the example code to create a bluetooth capable MIDI instument. Please view the manual for information on usage.
category=Device Control
url=https://github.com/ARAM-USA-Support/ARAM_Metal_Orchestra
architectures=*s
